<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 3.2.0.1 setup script by Piotr Przybylski <piotrprz@gmail.com>
 * Date: Fri, 10 Jul 2009 05:30:19 +0000
 */

/* Servers configuration */
$i = 0;

/* Server: localhost [1] */
$i++;
$cfg['Servers'][$i]['verbose'] = '';
$cfg['Servers'][$i]['host'] = 'localhost';
$cfg['Servers'][$i]['port'] = '';
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['connect_type'] = 'tcp';
$cfg['Servers'][$i]['extension'] = 'mysqli';
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['user'] = 'root';
$cfg['Servers'][$i]['password'] = 'Philippians 4:8';

/* End of servers configuration */

$cfg['blowfish_secret'] = '4a56d1b7ebb413.20059430';
$cfg['DefaultLang'] = 'en-utf-8';
$cfg['ServerDefault'] = 1;
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';

$cfg['ForceSSL'] = true;
?>